#!/bin/sh

# Run Prettier on staged files and add them to the commit
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js\|\.ts$')

if [ -n "$staged_files" ]; then
  echo "Running Prettier on staged files..."
  echo "$staged_files" | xargs npm run prettier
  echo "$staged_files" | xargs git add
fi

# Run ESLint with --fix on staged files and add them to the commit
if [ -n "$staged_files" ]; then
  echo "Running ESLint with --fix on staged files..."
  echo "$staged_files" | xargs npm run lint:fix || true
  echo "$staged_files" | xargs git add
fi
