name: 'PR Verification'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: write # Changed from write to read for security

jobs:
  verify:
    runs-on: ubuntu-latest
    name: PR Verification
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint --if-present

      - name: Run Prettier and format files
        run: npm run prettier --if-present

      - name: Commit formatted files if necessary
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Formatting changes detected. Adding changes to the commit."
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "chore: Formatting automatically applied by PR-Verify github action."
            git push
          else
            echo "No formatting changes detected."
          fi

      - name: Run tests
        run: npm run test:cov --if-present
