name: 'PR Verification'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: write # Grants the necessary write permissions to push changes

jobs:
  verify:
    runs-on: ubuntu-latest
    name: PR Verification
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Prettier and format files
        run: npm run prettier

      - name: Commit formatted files if necessary
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Formatting changes detected. Adding changes to the commit."
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "chore: Formatting automatically applied by PR-Verify github action."
            git push

      - name: Run tests
        run: npm run test:cov
